import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Hero from '@/components/Hero'
import Country from '@/components/Country'



const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />

        
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='bg-gradient-to-r from-gray-200 via-gray-400 to-gray-600 text-white font-lora'>

      
      
      
      <Country/>
      <Hero/>
      

        
      </main>
    </>
  )
}
